- name: "秘塔AI搜索"
  icon: "fab fa-airbnb"
  url: "https://metaso.cn/?q="
- name: "Github"
  icon: "fab fa-github"
  url: "https://github.com/search?q="
- name: "Linux 命令"
  icon: "fab fa-linux"
  url: "https://linux.lylme.com/list.html#!kw="
- name: "百度翻译"
  icon: "fas fa-language"
  url: "https://fanyi.baidu.com/#auto/zh/"
- name: "Google翻译"
  icon: "fab fa-google-plus"
  url: "https://translate.google.com/?sl=auto&tl=zh-CN&text="
- name: "iconfont"
  icon: "fas fa-icons"
  url: "https://www.iconfont.cn/search/index?searchType=icon&q="
- name: "Crx搜搜"
  icon: "fab fa-chrome"
  url: "https://www.crxsoso.com/search?store=chrome&keyword="