- name: "微信传输助手"
  color: "#1ba784"
  icon: "fab fa-weixin"
  url: "https://filehelper.weixin.qq.com"
- name: "微信传输助手"
  color: "#1ba784"
  icon: "fab fa-weixin"
  url: "https://filehelper.weixin.qq.com"